### ISSUE TITLE
Some more rules we should look into for code cleanliness

### ISSUE THREAD

**Issue by JakeSidSmith** [dabapps/eslint-config-dabapps#18]
http://eslint.org/docs/rules/no-extra-semi
http://eslint.org/docs/rules/semi-spacing
http://eslint.org/docs/rules/no-debugger

**Comment by manosim** [comment]
Also tried this plugin on a side project and looks pretty useful https://www.npmjs.com/package/eslint-plugin-import

**Comment by JakeSidSmith** [comment]
If that handles case sensitivity, that'd be fucking awesome.

**Comment by JakeSidSmith** [comment]
If not, there are some babel / browserify plugins that'd help us on that front.

**Comment by JakeSidSmith** [comment]
Probably more relevant to #16
